# Ces serveurs ont été définis lors de l'installation :
 
server ntp1.prd.questel.fr iburst
server ntp2.prd.questel.fr iburst
server ntp3.prd.questel.fr iburst
server ntp4.prd.questel.fr iburst
 
# Utiliser des serveurs publics du projet pool.ntp.org.
# Pensez à rejoindre le pool (http://www.pool.ntp.org/join.html).
 
# Enregistrer la dérive de l'horloge système (gain ou perte de temps).
driftfile /var/lib/chrony/drift
 
# Permet d’ajuster brutalement l’horloge système lors des 3 premières mises à jour
# si le décalage est supérieur à 1 seconde.
makestep 1.0 3
 
# Active la synchronisation du noyau avec l'horloge matérielle (RTC).
rtcsync
 
# Active le timestamp matériel sur toutes les interfaces compatibles.
#hwtimestamp *
 
# Augmente le nombre minimum de sources nécessaires pour ajuster l'horloge.
#minsources 2
 
# Autoriser l’accès aux clients NTP depuis le réseau local.
#allow 192.168.0.0/16
 
# Servir l’heure même si le serveur n’est pas synchronisé.
#local stratum 10
 
# Spécifie le fichier contenant les clés d’authentification NTP.
#keyfile /etc/chrony.keys
 
# Spécifie le répertoire des fichiers de logs.
logdir /var/log/chrony
